### ISSUE TITLE
Deberíamos mejorar las gráficas

### ISSUE THREAD

**Issue by indradecastro** [reverteiros/cursor#1]
Me han hablado de un *nuevo paquete* para plotear cosas guapas guapas, se llama **ggplot2** ([mira este link](https://www.google.es/search?q=ggplot2.&client=ubuntu&hs=p0&channel=fs&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiku5Xa4b_UAhXHuxQKHcR4B-EQ_AUICigB&biw=1366&bih=639)).  
Estas cosas son las cosas q se pueden hacer:

- plots con fondo gris
- solapar diferentes cosas
- graficas para publicacion
- combinar plots con las típicas "A", "B"...

qué te parece, @reverteiros ?

**Comment by reverteiros** [comment]
hecho!!
